---
title: "Data exploration: Feather River Snorkel Data"
author: ""
date: ""
output: 
  html_document:
    theme: flatly
---
# Overview {.tabset}

The objective of this document is to combine disparate snorkel datasets into one dataset by creating standard naming conventions and processing data so that it is consistent.

```{r, include = F}
library(googleCloudStorageR)
library(tidyverse)
library(lubridate)
library(janitor)
library(weathermetrics)
library(sf)
library(sp)
library(terra)
```

```{r, include = F}
# google cloud set up
gcs_auth(json_file = Sys.getenv("GCS_AUTH_FILE"))
gcs_global_bucket(bucket = Sys.getenv("GCS_DEFAULT_BUCKET"))

```

```{r, include = F}
# get data from google cloud
gcs_get_object(object_name = "juvenile-rearing-monitoring/seine-and-snorkel-data/feather-river/data-raw/feather_snorkel_and_catch.xlsx",
               bucket = gcs_get_global_bucket(),
               saveToDisk =  here::here("data-raw", "feather_snorkel_and_catch.xlsx"),
               overwrite = TRUE)


raw_snorkel_catch <- readxl::read_excel(here::here("data-raw", "feather_snorkel_and_catch.xlsx"))  

```

```{r}
# This chunk renames variables using snake case and make names more readable
snorkel_clean <- raw_snorkel_catch |> 
  clean_names() |> 
  glimpse()
```


```{r}
#checking temporal coverage
range(snorkel_clean$date, na.rm = TRUE)
```


